# -*- mode: ruby -*-
# vi: set ft=ruby ;

Vagrant.configure("2") do |config|
#  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.box = "utopic"
end

